=== B0bby19/XML-code/college.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.test.com"
xmlns="http://www.test.com"
elementFormDefault="qualified">
	<xs:element name="college">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="teacher" maxOccurs="5" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[a-zA-Z]+"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="subject" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="student" maxOccurs="40" minOccurs="0">
					<xs:complexType>
						<xs:all>
							<xs:element name="rollno" type="xs:integer"/>
							<xs:element name="name">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[a-zA-Z]+"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="subject" type="xs:string"/>
							<xs:element name="marks">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:minInclusive value="0"/>
										<xs:maxInclusive value="100"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
</xs:schema>

=== B0bby19/XML-code/college.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="college.xslt"?>
<college xmlns="http://www.test.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.test.com college.xsd">
	<teacher>
		<name>Naresh</name>
		<subject>web tech</subject>
	</teacher>
	<teacher>
		<name>Ajaya</name>
		<subject>DSA</subject>
	</teacher>
	
	<student>
		<rollno>1</rollno>
		<name>Basant</name>
		<subject>web tech</subject>
		<marks>75</marks>
	</student>
	<student>
		<rollno>2</rollno>
		<name>Aditya</name>
		<subject>web tech</subject>
		<marks>35</marks>
	</student>
	<student>
		<rollno>3</rollno>
		<name>Saroj</name>
		<subject>web tech</subject>
		<marks>99</marks>
	</student>
	<student>
		<rollno>4</rollno>
		<name>Bishnu</name>
		<subject>web tech</subject>
		<marks>5</marks>
	</student>
	<student>
		<rollno>5</rollno>
		<name>Kamal</name>
		<subject>web tech</subject>
		<marks>70</marks>
	</student>
</college>
