=== B0bby19/XML-code/employee.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.test.com"
xmlns="http://www.test.com"
elementFormDefault="qualified">
	<xs:element name="college">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="employee" maxOccurs="2">
					<xs:complexType>
						<xs:sequence>
							<!-- firstname element with language attribute -->
							<xs:element name="firstname">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="language" type="xs:string" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="lastname">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[a-zA-Z]+"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="gender">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="Male|Female"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="address">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:whiteSpace value="preserve"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="email" type="xs:string"/>
							<xs:element name="age">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="0"/>
										<xs:maxInclusive value="120"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="district">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Kathmandu"/>
										<xs:enumeration value="Bhaktapur"/>
										<xs:enumeration value="Lalitpur"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="password">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="8"/>
										<xs:maxLength value="25"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== B0bby19/XML-code/employee.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="employee.xslt"?>
<college xmlns="http://www.test.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.test.com employee.xsd">
	<employee>
		<firstname language="english">Ram</firstname>
		<lastname>tharu</lastname>
		<gender>Male</gender>
		<address>ktm</address>
		<email>ram@javatpoint.com</email>
		<age>39</age>
		<district>Kathmandu</district>
		<password>sdfsdsddsf</password>
	</employee>
</college>
