=== B0bby19/XML-code/student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="student.xslt"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.something.com.np" xmlns="http://www.something.com.np" elementFormDefault="qualified">

<xs:element name="college">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="student">
                <xs:complexType>
                    <!-- <xs:all></xs:all> = no sequence --> 
                    <xs:sequence> 
                        <!-- roll no with an attribute of  joinDate  that takes type of date as an attribute value -->
                        <xs:element name="rollNo" >
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="joinDate" type="xs:date"
                                        use="required"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>

                        <!-- name and last name of element of that takes simple string in the content -->
                        <!-- <xs:element type="xs:string" name="firstName" default="fname"/> -->
                        <!-- putting alphabet restriciton on first name as well -->
                        <xs:element name="firstName">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <!-- * : zero or more -->
                                    <!-- + : one or more -->
                                    <xs:whiteSpace value="collapse"/>
                                    <xs:pattern value="[a-zA-Z]+"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>

                        <xs:element type="xs:string" name="lastName" default="lname"/>

                        <!-- setting the range of the dataType as well ( this is called assets )  -->
                        <!-- <xs:element name="age" type="xs:integer"/> -->
                        <xs:element name="age">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="0"/>
                                    <xs:maxInclusive value="120"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>

                        <!-- restriction with already defined values ( no external values is allowed ) -->
                        <!-- using enums for certain choices and restriction of inputs -->
                        <xs:element name="district">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:whiteSpace value="collapse"/>
                                <xs:enumeration value="Kathmandu"/>
                                <xs:enumeration value="Pokhara"/>
                                <xs:enumeration value="Bhaktapur"/>
                                <xs:enumeration value="Lalitpur"/>
                                <xs:enumeration value="Baglung"/>
                                <xs:enumeration value="Ramechhap"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>

                        <!-- gender -->
                        <xs:element name="gender">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <!-- Either use pattern or enums -->
                                    <xs:whiteSpace value="collapse"/>
                                <xs:enumeration value="Male"/>
                                <xs:enumeration value="Female"/>
                                <xs:enumeration value="Others"/>
                                <!-- <xs:pattern value="Male|Female|Others"/> -->
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="address">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:whiteSpace value="collapse"/>
                            </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="password">
                            <xs:simpleType>
                                <xs:restriction  base="xs:string">
                                    <xs:whiteSpace value="collapse"/>
                                    <!-- <xs:length value="8" /> -->
                                    <xs:minLength value="8"/>
                            </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <!-- <xs:element name="phone">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="/d{10}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element> -->
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <!-- <xs:element name="teacher"></xs:element> -->
        </xs:sequence>
    </xs:complexType>
</xs:element>


</xs:schema>

<!-- <namespace:facets> = <xs:sequence> example -->

<!-- if used choice facets only one of the nested elements can be seelcted
if used all then any of the elements are allowed with no predetermined sequnece
if used sequence then any of the predermined elements are to be used with the same predetermined sequnece  -->

<!-- simpletype, complexType, length, minLength etc are facets -->
<!-- the restriction for dataTypes as well are called facets -->
<!-- facets work on the inner layer of restriction for the dataTypes -->


<!-- aru le use garne DTD is public and DTD
created by developers to use by themselves is private DTD -->

=== B0bby19/XML-code/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="student.xslt"?>
<!-- xmlns is the default namespace -->
<!-- use xsi to represent the anothe namespace -->
<college xmlns="http://www.something.com.np" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.something.com.np student.xsd">
	<student>
		<rollNo joinDate="2022-02-22">
			1
		</rollNo>
		<firstName>
		 Basant
		</firstName> 
		<lastName>
			Joshi
		</lastName>
		<age>
			20
		</age>
		<district>
			Ktm
		</district>
		<gender>
			Male
		</gender>
		<address>
			Kalopool
		</address>
		<password>
			12345678
		</password>
	</student>
</college>
